stages:
  - deploy
  - cleanup

.default:
  image: ubuntu:22.04
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    TF_IN_AUTOMATION: "true"
    REGION: ap-northeast-1
    ENABLE_VPC_FLOW_LOGS: "true"
  before_script:
    - apt-get update
    - apt-get install -y curl unzip jq python3 python3-pip make git awscli gnupg
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - source /etc/os-release && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com ${UBUNTU_CODENAME} main" > /etc/apt/sources.list.d/hashicorp.list
    - apt-get update && apt-get install -y terraform
    - python3 -m pip install --upgrade pip
    - export PATH="$HOME/.local/bin:$PATH"
    - chmod +x checks/*.sh

.deploy_template:
  extends: .default
  stage: deploy
  environment:
    name: demo
    action: start

deploy_demo:
  extends: .deploy_template
  rules:
    - if: '$PIPELINE_MODE == "deploy-only"'
  script:
    - make init
    - make apply ENV_FILE=.env.ci
    - mkdir -p output
    - terraform -chdir=iac output -json > output/deployment-summary.json || true
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - iac/terraform.tfstate
      - iac/terraform.tfstate.backup
      - output/deployment-summary.json
      - output/ccc-vpc/

destroy_demo:
  extends: .default
  stage: cleanup
  needs:
    - job: deploy_demo
  rules:
    - if: '$PIPELINE_MODE == "deploy-only"'
  when: manual
  allow_failure: false
  environment:
    name: demo
    action: stop
  script:
    - make destroy ENV_FILE=.env.ci || true
