stages:
  - deploy
  - validate
  - cleanup

.default:
  image: ubuntu:22.04
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    TF_IN_AUTOMATION: "true"
    REGION: ap-northeast-1
    ENABLE_VPC_FLOW_LOGS: "true"
  before_script:
    - apt-get update
    - apt-get install -y curl unzip jq python3 python3-pip make git awscli gnupg
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - source /etc/os-release && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com ${UBUNTU_CODENAME} main" > /etc/apt/sources.list.d/hashicorp.list
    - apt-get update && apt-get install -y terraform
    - python3 -m pip install --upgrade pip prowler
    - export PATH="$HOME/.local/bin:$PATH"
    - curl -L -o /tmp/privateer.tar.gz https://github.com/privateercloud/privateer/releases/download/v0.13.2/privateer_Linux_x86_64.tar.gz
    - tar -xzf /tmp/privateer.tar.gz -C /usr/local/bin privateer
    - chmod +x checks/*.sh

.deploy_template:
  extends: .default
  stage: deploy
  environment:
    name: demo
    action: start

.validate_template:
  extends: .default
  stage: validate

deploy_demo:
  extends: .deploy_template
  rules:
    - if: '$PIPELINE_MODE == "combined"'
    - if: '$CI_COMMIT_BRANCH'
      when: manual
  script:
    - make init
    - make apply ENV_FILE=.env.ci
    - mkdir -p output
    - terraform -chdir=iac output -json > output/deployment-summary.json || true
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - iac/terraform.tfstate
      - iac/terraform.tfstate.backup
      - output/deployment-summary.json
      - output/ccc-vpc/

validate_demo:
  extends: .validate_template
  needs:
    - job: deploy_demo
      artifacts: true
  rules:
    - if: '$PIPELINE_MODE == "combined"'
    - if: '$CI_COMMIT_BRANCH'
      when: manual
  script:
    - make validate-ci ENV_FILE=.env.ci
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - output/ci/
      - output/ccc-vpc/ccc-vpc.json
      - output/runtime/runtime-guard.json
      - output/validate/
  allow_failure: false

destroy_demo:
  extends: .default
  stage: cleanup
  needs:
    - job: deploy_demo
  when: manual
  allow_failure: false
  environment:
    name: demo
    action: stop
  rules:
    - if: '$PIPELINE_MODE == "combined"'
    - if: '$CI_COMMIT_BRANCH'
      when: manual
  script:
    - make destroy ENV_FILE=.env.ci || true
